package com.mrsoft.arabicreference.shared.kernel.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    CONFLICT,
    VALIDATION_FAILED,
    FORBIDDEN_OPERATION,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DISABLED,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_REUSED,
    PASSWORD_CHANGE_REQUIRED,
    RATE_LIMITED,
    SERVICE_UNAVAILABLE,
    METHOD_NOT_ALLOWED,
    INTERNAL_ERROR
}
