package com.mrsoft.arabicreference.identity.domain;

public enum AuditEventType {
    ADMIN_LOGIN_SUCCEEDED,
    ADMIN_LOGIN_FAILED,
    ADMIN_LOGOUT,
    ADMIN_PASSWORD_CHANGED,
    ADMIN_USER_CREATED,
    ADMIN_USER_UPDATED,
    ADMIN_USER_ACTIVATED,
    ADMIN_USER_DEACTIVATED,
    ADMIN_USER_UNLOCKED,
    ADMIN_PASSWORD_RESET,
    ADMIN_ROLE_CREATED,
    ADMIN_ROLE_UPDATED,
    ADMIN_ROLE_ASSIGNED,
    ADMIN_ROLE_REMOVED
}
